spring.application.name=inventario
spring.datasource.url=jdbc:mysql://localhost:3306/inventario_pruebas
spring.datasource.username= root
spring.datasource.password= root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.encoding=UTF-8
server.port=8080
# 1.Crear las tablas en la base de datos
# spring.jpa.hibernate.ddl-auto=create
# 2.Actualizar las tablas (recomendado para desarrollo)
spring.jpa.hibernate.ddl-auto= create
#Actualizar contraseña
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=degomeca2@gmail.com
spring.mail.password=vbjlelrzzsydjkkc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.urlFront=http://localhost:8080/login/reset-password?token=